version: '3.8'

services:
  sovrabase:
    image: ghcr.io/ketsuna-org/sovrabase:latest
    # Pour build local, d√©commentez :
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    container_name: sovrabase
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./config.yaml:/config.yaml:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - sovrabase-data:/data

volumes:
  sovrabase-data:
    driver: local
